oasis-tcs/openc2-oc2ls

oc2ls-v1.0-csd01.md

initial creation of OpenC2 Language Specification CSD rev 01

initial csd rev 01 in markdown

---

oc2ls-v1.0-wd02-0wip.md

this is exact copy so changes will show up in future commits

cp csd01 to wd02 to start

---

oc2ls-v1.0-wd02-0wip.md

At LSC session of day 1 of face to face Jan 19, 2018, the LSC agreed to this change to remove the word synchronously

Issue 8 Synchronously

---

oc2ls-v1.0-wd02-0wip.md

Reviewed and agreed to at lsc session of day 1 of face to face Jan 10, 2018

Issue 4 SHOULD/SHALL case notation

---

oc2ls-v1.0-wd02-0wip.md

add target summary table

---

oc2ls-v1.0-wd03.md

Issue 29 - create wd03 base

---

oc2ls-v1.0-wd03.md

update document version and date

---

oc2ls-v1.0-wd03.md

Addresses Issue #31 
Formatting changes applied to this commit.

apply editorial formatting changes

---

oc2ls-v1.0-wd03.md

Addresses Issue #31 
Applies content changes that are editorial in nature.

apply editorial content changes

---

oc2ls-v1.0-wd03.md

update action/target definitions

---

oc2ls-v1.0-wd03.md

Sentence removed that contradicted conformance requirement.

apply editorial comment to conformance section

---

oc2ls-v1.0-wd03.md

add row to revision history

---

oc2ls-v1.0-wd04.md

add property tables for ip_connection

Issue48 ip connection

---

oc2ls-v1.0-wd04.md

All material changes were discussed at the 02/27/2018 LSC Meeting: https://meet.lucidmeetings.com/meeting/184673.

apply material changes to wd04

---

oc2ls-v1.0-wd04.md

adding extensibility specifically in target section to address ballot comments

target extensibility wording

---

oc2ls-v1.0-wd05-wip.md

editorial for new wd

---

oc2ls-v1.0-wip.md

It was also agreed to include this sentence in JADN Annex (which needs to be created).

Issue 105. This text and placement agreed to at 7/31/2018 LSC. 

---

oc2ls-v1.0-wip.md

update intro section

---

oc2ls.md

remove response code 301

---

oc2ls.md

replace 'target' with 'TARGET'

---

oc2ls.md

removed term 'mandatory' from section 2, 4

---

oc2ls.md

replace 'implementations' with 'OpenC2 Consumer' in Section 3.1.5

---

oc2ls.md

Addresses Issue #212 "define nsid" and Issue #256 "importing extension profiles"

Issue 212 imports

---

oc2ls.md

Proposed resolution for Issues #228, #230, #233, #142

Issue 230 normative

---

oc2ls.md

reword sentence for clarity

---

oc2ls.md

replace 'describes' with 'defines', reword sentence

---

oc2ls.md

remove reserved actions

---

oc2ls.md

add 'Note:' heading for clarification

---

oc2ls.md

Update Derived Enumeration description

---

oc2ls.md

remove reserved targets

---

oc2ls.md

This pull request marks Section 1.2, Terminology, as normative. This addresses Issue #189.

V1.0 csprd01 issue189

---

oc2ls.md

remove name length convention

---

oc2ls.md

add Message to list of defined terms

---

oc2ls.md

I tried syncing my working branch to the LS working branch.  But after doing that, the "files changed" link above shows *all* the changes that have already been accepted into the LS.  (WTF?)
To see just the new proposal, click on the second commit below.

Issue 235 pairs

---

oc2ls.md

This pull request addresses the following issues: #161, #162, #163, #164.

V1.0 csprd01 conformance

---

oc2ls.md

V1.0 csprd01 issue185

---

oc2ls.md

Addresses issue #134.
Alternative to Pull Request #237.

Split ipv4/v6, add ip_net and binary serialization

---

oc2ls.md

This pull request re-writes the "imported types" section in order to clarify the use of extensions within the language. 
This pull request addresses issue #156 and other extension-related issues. It is offered as a replacement for pull request #268.

re-write 'imported data' section, extensions

---

oc2ls.md

This pull request addresses issue #283.

re-write Section 2 for clarity, consistency

---

oc2ls.md

This pull request addresses the remaining comments in issue #227.

add (non-)normative statemens to sections; separate examples

---

oc2ls.md

This pull request addresses issue #275.

update definition of 'actuator'

---

oc2ls.md

Split IPv4/v6, add binary serialization

---

oc2ls.md

There are still a few last-minute updates to make, including a full editorial pass through the document. This working draft takes a snapshot to help with the final review.

prepare for new working draft

---

oc2ls.md

update extensions with fully-qualified namespace syntax

---

oc2ls.md

Update imports and examples

---

oc2ls.md

This addresses the ballot comments received during the review of wd12, noted in issue #301.

incorporated ballot comments

---

oc2ls.md

Addresses issue #308 and #301 part 3.

clarify message definition

---

oc2ls.md

Update Response structure

---

oc2ls.md

add statements for received Commands/Responses

---

oc2ls.md

specify no empty targets

---

oc2ls.md

remove integer serialization section

---

oc2ls.md

move and update 'Derived Enumerations' section

---

oc2ls.md

clarify binary serializations

---

oc2ls.md

apply suggested editorial changes

---

oc2ls.md

Add internationalized types

---

oc2ls.md

This pull request addresses issue #310. It should be applied after pull request #320 with a correction to remove "TBD" reference to new results definition section.

Update non-Target extensions to be hierarchical

---

oc2ls.md

This is a non-material change that was discovered during the ballot review of v1.0-wd13.

Fix error in example

---

oc2ls.md

Add minimum size of 1 to several types
Add lower bound of 0 to process/pid
Update syntax of Enum(type)
Add periods at end of some descriptions for consistency
Capitalize descriptions in IPv4/v6 connections
Change some formats to /format for consistency
Add unique to Features, Targets

Feature errata

---

oc2ls.md

Add actuators that we are, or should be, developing

add more actuators
